# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: managed.config.cloud.google.com/v1alpha1
kind: ClusterConfig
metadata:
  name: cert-issuer-ca-prod-clusters
  namespace: config-control
spec:
  description: deploy cert issuer to ca based mcs prod-clusters
  managedCSRefs:
    - name: prod-clusters
  selector:
    matchLabels:
      location: ca
  syncSpec:
    sourceType: git
    sourceFormat: unstructured
    git:
      repo: https://github.com/GoogleContainerTools/kpt-samples.git
      dir: cert-issuers
      branch: main
      auth: none
      period: 1m
